services:
  auctionservice:
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ConnectionStrings__DCS=Host=postgres;Port=5432;Database=AuctionDB;Username=postgres;Password=1A2B3C
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "8081:8081"

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1A2B3C
      POSTGRES_DB: AuctionDB
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoroot
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:latest
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15672:15672" # Management UI
      - "5672:5672" # AMQP protocol port

volumes:
  postgres_data:
  mongo_data:
